### ISSUE TITLE
Write/Add command for toggling brake mode

### ISSUE THREAD

**Issue by snowpuppy** [Team1100/FRCChargedUp#10]
The purpose of this task is to write/add a command for toggling brake mode on the Drive motors. This will allow the driver to stop the robot on the teeter totter.

**Comment by snowpuppy** [comment]
This has been written. It just needs to be reviewed and pulled in.

**Comment by Jack-Tommaney** [comment]
Is this done?  Can I close out this issue?

**Comment by snowpuppy** [comment]
This has been added.
