### ISSUE TITLE
Write basic hand commands

### ISSUE THREAD

**Issue by snowpuppy** [Team1100/FRCChargedUp#12]
Write 4 commands as follows. Note that commands 1 and 2 will spin the hand motor in the same direction and commands 3 and 4 will spin the hand motor in the same direction.
1. IntakeCone
2. IntakeCube
3. ExpelCone
4. ExpelCube

**Comment by AshleyY06** [comment]
It is commands 1 and 4 that spin the motor in the same direction and commands 2 and 3 spin in the same direction.

**Comment by snowpuppy** [comment]
The commands have been added. Two of them need to be bound to buttons. It might make sense to bind them to the triggers. If we bind them to the triggers, we may want versions of the commands that  get speed from an xbox axis so that the operator has some control over the speed of the intake motors.
